// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/telemt-panel/DataFirst.tsx": () => import("../components/mockups/telemt-panel/DataFirst.tsx"),
  "./components/mockups/telemt-panel/NetworkTopology.tsx": () => import("../components/mockups/telemt-panel/NetworkTopology.tsx"),
  "./components/mockups/telemt-panel/TerminalNative.tsx": () => import("../components/mockups/telemt-panel/TerminalNative.tsx")
};
